### ISSUE TITLE
Unsupported webpack version

### ISSUE THREAD

**Issue by sammyrulez** [OutWatch/outwatch#148]
Trying the "getting started" when it run the sbt command "fastOptJS::webpack" I got this error
`
java.lang.RuntimeException: Unsupported webpack version
	at scala.sys.package$.error(package.scala:27)
	at scalajsbundler.Webpack$.writeConfigFile(Webpack.scala:70)
	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perScalaJSStageSettings$5.apply(ScalaJSBundlerPlugin.scala:702)
	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perScalaJSStageSettings$5.apply(ScalaJSBundlerPlugin.scala:701)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (compile:fastOptJS::scalaJSBundlerWebpackConfig) Unsupported webpack version
`

**Comment by sammyrulez** [comment]
UPDATE:
Updating the version of scalajs-bundler to 0.9.0  solves the error. The issue is on the seed project

**Comment by LukaJCB** [comment]
Thanks for filing this issue, we'll try to get it fixed asap :)

**Comment by LukaJCB** [comment]
Webpack updated, thanks again
