### ISSUE TITLE
Bench project does not work

### ISSUE THREAD

**Issue by cornerman** [OutWatch/outwatch#301]
We have somehow broke the bench project. We should test it in the CI as well.

Error:
```
TypeError: ib.jsdom is not a function
    at Object.<anonymous> (/home/cornerman/projects/outwatch/bench/target/scala-2.12/scalajs-bundler/main/bench-opt.js:953:482)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at [stdin]:38:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)

```

**Comment by cornerman** [comment]
Fixed with #303
